version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_PASSWORD: "/simple-webapp/docker/password"
    DOCKER_REGISTRY_USERNAME: "/simple-webapp/docker/username"
    DOCKER_REGISTRY_URL: "/simple-webapp/docker/url"
    
phases:
  install:
    runtime-versions:
       python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "running test"
      - echo "building docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest" .
  post_build:
    commands:
      - echo "docker build was completed"
      - echo "echo Pushing the Docker image..."
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-webapp
